export enum ActionTypes {
    ADD_ORDER = 'ADD_ORDER',
    UPDATE_ORDER = 'UPDATE_ORDER',
    UPDATE_ORDER_IN_EDIT = 'UPDATE_ORDER_IN_EDIT',
    DELETE_ORDER = 'DELETE_ORDER',
    EDIT_ORDER = 'EDIT_ORDER',
    CLICKED_ORDER = 'CLICKED_ORDER'
}


