export enum ActionTypes {

    UPDATE_ORDER = 'UPDATE_ORDER',
    UPDATE_ORDER_IN_EDIT = 'UPDATE_ORDER_IN_EDIT',
    DELETE_ORDER = 'DELETE_ORDER',
    EDIT_ORDER = 'EDIT_ORDER',
    CLICKED_ORDER = 'CLICKED_ORDER',
    ADD_NEW_ORDER = 'ADD_NEW_ORDER',

    OPEN_MY_PROFILE = 'OPEN_MY_PROFILE',
    EXPORT_ALL = 'EXPORT_ALL',
    IMPORT_ALL = 'IMPORT_ALL',
    IMPORT_FILE_UPLOADED = 'IMPORT_FILE_UPLOADED',
    IMPORT_DIALOG_OPEN = 'IMPORT_DIALOG_OPEN',

    DELETE_SIDUR = 'DELETE_SIDUR',
    RENAME_SIDUR = 'RENAME_SIDUR',
    ADD_NEW_SIDUR = 'ADD_NEW_SIDUR',
    CLONE_SIDUR = 'CLONE_SIDUR',
    CHOOSE_SIDUR = 'CHOOSE_SIDUR',
    ARCHIVE_SIDUR = 'ARCHIVE_SIDUR',

}


