export enum ActionsTypes {

    UPDATE_ORDER = 'UPDATE_ORDER',
    UPDATE_ORDER_IN_EDIT = 'UPDATE_ORDER_IN_EDIT',
    DELETE_ORDER = 'DELETE_ORDER',
    CLONE_ORDER = 'CLONE_ORDER',
    EDIT_ORDER = 'EDIT_ORDER',
    CLICKED_ORDER = 'CLICKED_ORDER',
    ADD_NEW_ORDER = 'ADD_NEW_ORDER',

    OPEN_MY_PROFILE = 'OPEN_MY_PROFILE',
    EXPORT_ALL = 'EXPORT_ALL',
    IMPORT_ALL = 'IMPORT_ALL',
    IMPORT_FILE_UPLOADED = 'IMPORT_FILE_UPLOADED',
    IMPORT_ORDERS_AS_TEXT = 'IMPORT_ORDERS_AS_TEXT',
    IMPORT_DIALOG_OPEN = 'IMPORT_DIALOG_OPEN',

    DELETE_SIDUR = 'DELETE_SIDUR',
    DELETE_FOREVER_SIDUR = 'DELETE_FOREVER_SIDUR',
    RENAME_SIDUR = 'RENAME_SIDUR',
    ADD_NEW_SIDUR = 'ADD_NEW_SIDUR',
    CLONE_SIDUR = 'CLONE_SIDUR',
    CHOOSE_SIDUR = 'CHOOSE_SIDUR',
    ARCHIVE_SIDUR = 'ARCHIVE_SIDUR',
    MOVE_TO_ACTIVE_SIDUR = 'MOVE_TO_ACTIVE_SIDUR',

    UPDATE_VEHICLE = 'UPDATE_VEHICLE',
    NEW_VEHICLE = 'NEW_VEHICLE',
    DELETE_VEHICLE = 'DELETE_VEHICLE',
    CHANGE_VIEW = 'CHANGE_VIEW'

}


