export enum ActionsTypes {
    /* Orders */

    UPDATE_ORDER = 'UPDATE_ORDER',
    UPDATE_ORDER_IN_EDIT = 'UPDATE_ORDER_IN_EDIT',
    DELETE_ORDER = 'DELETE_ORDER',
    CLONE_ORDER = 'CLONE_ORDER',
    EDIT_ORDER = 'EDIT_ORDER',
    CLICKED_ORDER = 'CLICKED_ORDER',
    ADD_NEW_ORDER = 'ADD_NEW_ORDER',

    /* Import - Export */
    OPEN_MY_PROFILE = 'OPEN_MY_PROFILE',
    EXPORT_ALL = 'EXPORT_ALL',
    IMPORT_ALL = 'IMPORT_ALL',
    IMPORT_FILE_UPLOADED = 'IMPORT_FILE_UPLOADED',
    IMPORT_ORDERS_AS_TEXT = 'IMPORT_ORDERS_AS_TEXT',
    IMPORT_DIALOG_OPEN = 'IMPORT_DIALOG_OPEN',

    /* Sidur */
    DELETE_SIDUR = 'DELETE_SIDUR',
    DELETE_FOREVER_SIDUR = 'DELETE_FOREVER_SIDUR',
    RENAME_SIDUR = 'RENAME_SIDUR',
    ADD_NEW_SIDUR = 'ADD_NEW_SIDUR',
    CLONE_SIDUR = 'CLONE_SIDUR',
    CHOOSE_SIDUR = 'CHOOSE_SIDUR',
    ARCHIVE_SIDUR = 'ARCHIVE_SIDUR',
    MOVE_TO_ACTIVE_SIDUR = 'MOVE_TO_ACTIVE_SIDUR',


    /* Vehicle */
    UPDATE_VEHICLE = 'UPDATE_VEHICLE',
    NEW_VEHICLE = 'NEW_VEHICLE',
    DELETE_VEHICLE = 'DELETE_VEHICLE',
    CHANGE_VIEW = 'CHANGE_VIEW',

    /* Sketch */
    NEW_SKETCH = 'NEW_SKETCH',
    DELETE_SKETCH = 'DELETE_SKETCH',
    RENAME_SKETCH = 'RENAME_SKETCH',
    CLONE_SKETCH = 'CLONE_SKETCH',
    CHOOSE_SKETCH = 'CHOOSE_SKETCH',

    /* Sketch Drive */
    UPDATE_SKETCH_DRIVE = 'UPDATE_SKETCH_DRIVE',
    DELETE_SKETCH_DRIVE = 'DELETE_SKETCH_DRIVE',
    REMOVE_ORDER_FROM_SKETCH_DRIVE = 'REMOVE_ORDER_FROM_SKETCH_DRIVE',

    /*pending Orders */
    CLICKED_PENDING_ORDER = 'CLICKED_PENDING_ORDER',
    CLICKED_CLOSE_PENDING_ORDER = 'CLICKED_CLOSE_PENDING_ORDER',
 
    CLICKED_REMOVE_PENDING_ORDER = 'CLICKED_REMOVE_PENDING_ORDER',
    CLICKED_MERGE_PENDING_ORDER = 'CLICKED_MERGE_PENDING_ORDER',
    CLICKED_SPLIT_PENDING_ORDER = 'CLICKED_SPLIT_PENDING_ORDER',
    CLICKED_CHANGE_PENDING_ORDER = 'CLICKED_CHANGE_PENDING_ORDER',
    CLICKED_CHANGE_TIME_PENDING_ORDER = 'CLICKED_CLOSE_PENDING_ORDER',
    CLICKED_REPLACE_EXISTING_PENDING_ORDER = 'CLICKED_REPLACE_EXISTING_PENDING_ORDER',
    CLICKED_PUBLIC_TRANSPORT_PENDING_ORDER = 'CLICKED_PUBLIC_TRANSPORT_PENDING_ORDER',
    CLICKED_ADD_TO_PENDING_PENDING_ORDER = 'CLICKED_ADD_TO_PENDING_PENDING_ORDER',

}


